### ISSUE TITLE
missing --upgrade flag

### ISSUE THREAD

**Issue by codl** [EdmundGoodman/update-bot#4]
`uv lock` on its own won't upgrade locked versions unless the previously locked versions are no longer suitable (yanked, no longer matches version specifiers in pyproject.toml, etc)

`uv lock --upgrade` is what you ought to be running if you want to update versions

See <https://docs.astral.sh/uv/concepts/projects/#upgrading-locked-package-versions>

**Comment by EdmundGoodman** [comment]
Good catch! Thanks for spotting this
